### ISSUE TITLE
Do not use "I" as a prefix for interface names.

### ISSUE THREAD

**Issue by laco0416** [horiuchi/dtsgenerator#15]
Official guideline says that:

> Do not use "I" as a prefix for interface names.

https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#names

I think dtsgenerator also should follow the convention. Thanks.

**Comment by horiuchi** [comment]
Thank you for your suggestion.
I think so, and I will fix interface names in the future.

**Comment by horiuchi** [comment]
I removed the default 'I' prefix.
