### ISSUE TITLE
dstgen output nothing

### ISSUE THREAD

**Issue by amarant** [horiuchi/dtsgenerator#16]
Hi,
I tried dstgen on those [jsonschema](https://github.com/highsource/w3c-schemas/tree/master/scripts/jsonschemas) and it didn't output anything, no even an error; any idea ?

Thanks.

**Comment by horiuchi** [comment]
This is the `dtsgen`s bug.
It make a request `type` property on root of the JSON Schema. But `type` is optional property on the spec.

**Comment by horiuchi** [comment]
And `dtsgen` generate the type definition from root level of input JSON Schema.
Those schema don't have the `properties` property on root level.

**Comment by horiuchi** [comment]
This bug is fixed.
