### ISSUE TITLE
Error: id is not found.

### ISSUE THREAD

**Issue by sueess** [horiuchi/dtsgenerator#22]
If I run: 
`dtsgen --out types.d.ts src/Schema.json `

I get the message "Error: id is not found.". What does it mean?

**Comment by horiuchi** [comment]
The `dtsgen` require `id` property in the root level of JSON Schema.

**Comment by sueess** [comment]
ok, I got that, thanks! Any way to declare a namespace for the generated type?

**Comment by horiuchi** [comment]
np :smile: 
The generated type name is followed by the rule.

`id`=`/path/to/name` => `type`= `declare namespace path { namespace to { interface name {} } }`

**Comment by sueess** [comment]
Tell me if I asked too much :).

-  What about "type": ["string", "null"]
- How do I reference from a schema file to a type inside another schema file? Such an example would be really helpfull.

**Comment by horiuchi** [comment]
> What about "type": ["string", "null"]

My expected generated type is `string`.

> How do I reference from a schema file to a type inside another schema file? Such an example would be really helpfull.

Thank you for using what is hard to understand usage.
About `$ref`, there is no difference between same file and other file. All reading file at same time becomes the target of a reference.
For example: https://github.com/horiuchi/dtsgenerator/blob/master/schema/apimeta.json and https://github.com/horiuchi/dtsgenerator/blob/master/schema/apibase.json

**Comment by horiuchi** [comment]
And now implementation include the bug: #24
If fix this bug, it may also change the specifications of `$ref`.

**Comment by sueess** [comment]
Nice! Thanks so much for your help.

> What about "type": ["string", "null"]
My expected generated type is string.

Sadly this ends in a
`Error:` unknown type: string,null

**Comment by horiuchi** [comment]
@sueess Sorry that error was fixed.

**Comment by sueess** [comment]
Great, thanks so much for your effort.
