### ISSUE TITLE
v0.9.3 does not contain transpiled JS files

### ISSUE THREAD

**Issue by gretro** [horiuchi/dtsgenerator#242]
When using the package at version 0.9.3, we get a `Error: Cannot find module '../src/cli'` error. This is because `cli.ts` is present, but not `cli.js`.

Was the package pushed prior to transpilation?

**Comment by horiuchi** [comment]
Oh sorry, I was mistaken.
I will release a new version soon.

**Comment by horiuchi** [comment]
v0.9.4 released
