### ISSUE TITLE
Can we choose whether to use namespace by command option？

### ISSUE THREAD

**Issue by studioTeaTwo** [horiuchi/dtsgenerator#251]
I don't need namespaces because: 

1. making this output as auto-generated single file
2. importing expressly interfaces to use in each component and services of Angular.
3. typing less

So, I want to get a file composing only `export interface` by command option.

P.S.
How do we use `--header` option? I guess that use for comment. But I can't have confidence in that.

**Comment by horiuchi** [comment]
Sorry, I don't understand it.
That namespace is needed to ensure the uniqueness.
Please let me know the actual problem.

If you want a short name, we can use [Aliases](https://www.typescriptlang.org/docs/handbook/namespaces.html#aliases) by `import` statement.

**Comment by horiuchi** [comment]
About `--header` option:

```
$ dtsgen --header '// header string' --out types.d.ts schema.json
```

**Comment by studioTeaTwo** [comment]
I agree your reply, If we build the libray that may be used by any unspecified app.
It needs the defensive proggramming.

I will explain my use case for this dtsgenerator.

I think there is a use case for only specified user app because the dts file generated by dtsgenerator is converted from swagger json and included **into front app space**.
It's not used expect the specified user app.
If the collision of name happens,  it probably should doubt  the error of styleguide or coding rule or anything to project management.
I don't even give a file name `d.ts` to the dts file generated by dtsgenerator. It's normaly `.ts`.

What do you think proposal of  a namespace **change** option？
Because, in case of input source by file format(not URL), top level namespace seems to be `Definitions`.(maybe the problem of server API documentation...)

Thank you.

**Comment by horiuchi** [comment]
Sure, I understand your proposal.

I have created the `dts-core` library for rewrite this project core feature.
That project's objective rewrite the source file printing method to the [TypeScript compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#creating-and-printing-a-typescript-ast) instead of string concatenation.
And I will add the hook method for some event, such as generating interface name, converting namespace name, and etc...

But now that project is not active...

**Comment by horiuchi** [comment]
Sorry late, I released v1 now.
Please use this feature for change namespace names.: https://github.com/horiuchi/dtsgenerator#advance-usage

**Comment by studioTeaTwo** [comment]
Thank you.
