### ISSUE TITLE
Fails for non-string examples

### ISSUE THREAD

**Issue by bricka** [horiuchi/dtsgenerator#267]
Hello! I think a recent change may have introduced an old bug about non-string examples. The particular code is here:

https://github.com/horiuchi/dtsgenerator/blob/553cb9465e87944c3b6c49072ab45ea960f4403e/src/writeProcessor.ts#L91-L93

When we do the split, we use `toString` to support non-string examples. However, we then pass the non-stringified `example` value into `protectComment`, which attempts to call `replace` on it.  This function doesn't exist, so we get this error:

```
TypeError: str.replace is not a function
    at WriteProcessor.protectComment (...\node_modules\dtsgenerator\src\writeProcessor.js:71:20)
    at WriteProcessor.outputJSDoc (...\node_modules\dtsgenerator\src\writeProcessor.js:88:55)
    at TypeDefinition.generateType (...\node_modules\dtsgenerator\src\typeDefinition.js:113:17)
    at TypeDefinition.doProcess (...\node_modules\dtsgenerator\src\typeDefinition.js:48:14)
```

Adding a type on `spec` might help prevent this problem, by declaring `example` as `string | number` instead of its current `any`.

Thank you!

**Comment by bricka** [comment]
Actually, it looks like `example` can even be an array? So it may truly be any, and `protectComment` just needs to call `toString` itself as well? Or maybe declare `example` as `string | number | object`?

**Comment by horiuchi** [comment]
Thank you for your bug report!
I will investigate the reason. But I think I should set the actual type to `spec` argument instead of `any`.
