### ISSUE TITLE
Open APIs Spec v3 Support

### ISSUE THREAD

**Issue by lacolaco** [horiuchi/dtsgenerator#270]
Current Open APIs Spec is in version 3.0.1

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md

Would you support that?

FYI: https://www.openapis.org/news/blogs/2016/10/tdc-structural-improvements-explaining-30-spec-part-2

**Comment by horiuchi** [comment]
Thank you for the suggestion!
I will support the current Open API v3.

**Comment by lacolaco** [comment]
Glad to hear that! I look forward to the update. 🙌

**Comment by horiuchi** [comment]
https://github.com/horiuchi/dtsgenerator/releases/tag/v1.0.0
v1 released!
