### ISSUE TITLE
$ref - Support for Remote Reference

### ISSUE THREAD

**Issue by i4got10** [horiuchi/dtsgenerator#286]
According to documentation https://swagger.io/docs/specification/using-ref/#syntax, it is possible to specify definitions in other file.

I have 2 files
- Definitions.yaml
- Api.yaml

Is it possible to import $ref from other file?

**Comment by horiuchi** [comment]
Yes, the `dtsgen` command is supported remote file reference.
This is the example: https://github.com/horiuchi/dtsgenerator/blob/master/test/snapshots/json-schema-draft-04/apimeta/apimeta.json#L13

The root `id` property is required by the `dtsgen`'s remote reference when loading on local contents.
The `id`'s value is used by `$ref`'s reference.

**Comment by i4got10** [comment]
Thanks, its working this way.
Here Yaml example

definitions.yaml

```yaml
swagger: '2.0'
definitions:
    address:
        id: address
        properties:
            city:
                type: string
            country:
                type: string
```

api.yaml
```yaml
swagger: '2.0'
definitions:
    ZoneinfoRequest:
        additionalProperties: false
        properties:
            point:
                $ref: 'address'
                description: address
        type: object
```

The only problem here, that types containing `id` became global and dont respect namespace anymore

```typescript
export interface Address {
    city?: string;
    country?: string;
}
declare namespace Definitions {
    export interface ZoneinfoRequest {
        /**
         * address
         */
        point?: Address;
    }
}
```

**Comment by horiuchi** [comment]
@i4got10 That can use namespaces.
For example when `id` value is `definitions/address`, the type name is `Definitions.Address`.
In this case, the type is in the `Definitions` namespace.
