### ISSUE TITLE
Bring back --prefix cli option

### ISSUE THREAD

**Issue by olegskl** [horiuchi/dtsgenerator#300]
Can you bring back the `--prefix` option? We use I-prefixed interfaces throughout the app and changing them all is difficult if we want to migrate to dtsgenerator v1.

TypeScript's guideline to avoid "I" as a prefix is limited to TypeScript development itself, not to the community. See https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines

**Comment by horiuchi** [comment]
Hmm...
It is true about I-prefixed interface.
If you need it now, You use this sample code: https://github.com/horiuchi/dtsgenerator/tree/master/example/add-prefix

I prefer to not use the I-prefix.
In TypeScript, there is no need to distinguish between `interface` and `class`. These are the `type`.

**Comment by jonborchardt** [comment]
WFIW

I agree on not using I as a prefix for interfaces... migrating the code over time might make sense.

https://softwareengineering.stackexchange.com/questions/117348/should-interface-names-begin-with-an-i-prefix
