### ISSUE TITLE
Add --namespace <namespace> CLI to override default namespaces

### ISSUE THREAD

**Issue by DavidBiesack** [horiuchi/dtsgenerator#301]
When running `dtsgen -o types.d.ts < openapi.yaml`, the emitted file contains a namespace based on the JSON path to the schemas, namely
```
declare namespace Definitions { ... }
```
Unfortunately, when one converts the file from OpenAPI 2.0 to OpenAPI 3.0, the location of the schemas is now in components schemas and the output is
```
declare namespace Components {
    namespace Schemas {
```

I'd like the output to be independent of the JSON path where the schemas are found, as these names are really unrelated to the API itself; they are merely artifacts of the OpenAPI specification and layout.

I propose adding a `--namespace <namespace>` option in the CLI, so one could do
```
dtsgen -o petstore.d.ts --namespace PetStore << petstore.yaml
```
to get
```
declare namespace PetStore { ... }
```

If you like, I can submit a PR to support this. It also allows one to use `--namespace ~none~` so the emitted types are not in a namespace at all.

**Comment by horiuchi** [comment]
[v1.2.0](https://github.com/horiuchi/dtsgenerator/releases/tag/v1.2.0) released
