### ISSUE TITLE
Question: json-schema to typescript or typescript to json-jschema

### ISSUE THREAD

**Issue by no-more** [horiuchi/dtsgenerator#31]
Hi,

I'm new to typescript and json-schema and I would like to know which one is the more complete. I want to use the most complete one as base in order to generate the other one. At first glance I would think json-schema is more complete and polyvalent than typescript.

Could someone confirm this?

An idea: it would be great to be able to be bidirectionnal.

Thanks for your response and for your work on this project.

**Comment by sebilasse** [comment]
confirmative.

**Comment by horiuchi** [comment]
JSON-Schema spec is covering a wide range than TypeScript.
I think it is enough to convert single direction from JSON Schema to TypeScript.

**Comment by horiuchi** [comment]
I close this issue, because of stopped discussion.
