### ISSUE TITLE
Feature Request: Allow non-optional keys when schema has default.

### ISSUE THREAD

**Issue by mastermatt** [horiuchi/dtsgenerator#314]
I use this lib primarily for server-side consumption, so my controllers can have types for request bodies and query params. 
`dtsgenerator` marks interface keys as optional (`?`) when the schema does not mark them as required, which makes sense from the client-side perspective, but from the server-side, if the attribute has a default value the generated TS interface should not consider the key as optional. 

My solution to date is to use a wrapper script that dives into the Definition schemas (Swagger v2) and sets keys as required if they have a default set, before throwing the spec into `dtsgenerator`.

```ts
async function main() {
  const spec = JSON.parse(fs.readFileSync(swaggerPath, { encoding: "utf-8" }));
  for (const schema of Object.values(spec.definitions)) {
    fixDefaults(schema);
  }
  const result = await dtsGenerator({
    contents: [spec],
    namespaceName: "MyAPI",
  });
  fs.writeFileSync(outPath, result, { encoding: "utf-8" });
}

function fixDefaults(schema) {
  if (!schema.properties) {
    return;
  }

  if (!schema.required) {
    schema.required = [];
  }

  for (const [k, subSchema] of Object.entries(schema.properties)) {
    if ("default" in subSchema && !schema.required.includes(k)) {
      schema.required.push(k);
    }

    if (subSchema.type === "object") {
      fixDefaults(subSchema);
    }
  }
}
```

I thought I would open this as an issue instead of a PR to see if this feature has any buyin.
It would mean adding an optional arg, called something?, and the implementation would need to be smarter than my workaround since determining if an attribute has a default varies from JSON Schema/Swagger/OpenAPI.

**Comment by horiuchi** [comment]
@mastermatt Thank you for your suggestion.
But that case's types of TypeScript are optional arguments.

In fact, bellow case's declare type is the optional argument.
```ts
function f(a: string, b?: string = 'optional'): void {}
```
to
```d.ts
function f(a: string, b?: string): void;
```

If you need not optional argument type for server-side, you define the new type like as bellows.
```
// original declare type
interface A {
  a: string;
  b?: string;
}

// new defined type
interface A_DefaultValue {
  b: string;
}
type ServerSideA = A & A_DefaultValue;
```

**Comment by mastermatt** [comment]
@horiuchi you're right. Rendering two different interfaces/types that include with and without defaults is the way to go instead of an extra argument.

Should I go ahead and create a PR that adds this functionality?
