### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by no-more** [horiuchi/dtsgenerator#32]
Hi,
I'm on windows with npm 3.5.3 and node 4.2.5 but I can't install this package I have the following error:

npm ERR! fibers-scriby@1.0.8 install: 'node build.js || nodejs build.js'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers-scriby@1.0.8 install script 'node build.js || nodejs build.js'.

**Comment by horiuchi** [comment]
My local environment is success to install.

```
$ node -v
v4.3.1
$ npm -v
3.8.0
$ npm install -g dtsgenerator
```

**Comment by horiuchi** [comment]
But I want to replace the `asyncblock` library to the standard `Promise`.

**Comment by no-more** [comment]
Thanks I've upgraded and it's now working !!!
