### ISSUE TITLE
Can't resolve remote schemas correctly

### ISSUE THREAD

**Issue by f1cognite** [horiuchi/dtsgenerator#323]
I tried to run `npx dtsgenerator --url https://storage.googleapis.com/cognitedata-api-docs/openapi.0.5.json` and it failed with `Error: The $ref targets root is not found: https://storage.googleapis.com/cognitedata-api-docs/api-acls-0.8.4s.json#/components/schemas/cogniteCapability`.

I also ran Swagger-CLI: `npx swagger-cli validate https://storage.googleapis.com/cognitedata-api-docs/openapi.0.5.json` which stated that the spec is valid.

**Comment by horiuchi** [comment]
probably, it's the same issue by #321

**Comment by f1cognite** [comment]
This is still a problem in `2.0.6`

**Comment by adriengibrat** [comment]
@horiuchi you should close this issue, it seems to be fixed ;)

```
npx dtsgenerator --url https://storage.googleapis.com/cognitedata-api-docs/openapi.0.5.json
```
is now OK with v2.3.1

**Comment by horiuchi** [comment]
@adriengibrat Thank you for your confirmation! :+1:
