### ISSUE TITLE
Single quote option

### ISSUE THREAD

**Issue by Christian24** [horiuchi/dtsgenerator#327]
Hello,

is it possible to generate source files which use single quotes instead of double quotes? This would be nice to have to have the generated code uniform with the written code.

**Comment by horiuchi** [comment]
@Christian24 Thank you for using the `dtsgenerator`.
I'm favorite to use the single quote on TypeScript code.
I will think to add the option.

Now, I use the `tslint` fixing for quotes, such as, `tslint -p . --fix`.

**Comment by Christian24** [comment]
Cool, thanks! I think we are using TSLint to fix at the moment as well. :)

If you need help adding this, let me know. I might be able to help if you point me into the right direction. 

Thank you for creating and maintaining dtsgenerator. It is a joy to work with.

**Comment by horiuchi** [comment]
In v3, you can do that by enabling the @dtsgenerator/single-quote plugin!
