### ISSUE TITLE
convert union types to types

### ISSUE THREAD

**Issue by Christian24** [horiuchi/dtsgenerator#328]
Hi,

This is more a suggestion/question than a bug. Enums are converted to union types like so:
```ts
status: 'active' | 'ended' | 'preparing';
```
This works well. However, I recently stumbled upon large enums and a sonar tslint rule that only allows for three union type members:
https://github.com/SonarSource/SonarTS/blob/master/sonarts-core/docs/rules/max-union-size.md

Sonar implies it is a better practice to define types than using union types. So that the example becomes:
```ts
type statusType =  'active' | 'ended' | 'preparing';
status: statusType;
```
I like the general idea, because the enum suddenly becomes reusable. 

What do you think?

**Comment by polomani** [comment]
Something that I faced as well

**Comment by horiuchi** [comment]
I think this is a good idea too.

But this idea has one problem.
I don't have the plan to create the unique type name for the union type.

**Comment by Christian24** [comment]
In our case it is mostly just the field name. So, maybe just the field name + Type could be used?

**Comment by silesky** [comment]
I generally have been fine extracting the Union types doing something like:

Type NewUnion = Components.Foo[‘MyUnion’]

**Comment by horiuchi** [comment]
This issue is old and has been closed. If you need it, please reopen it again.
