### ISSUE TITLE
strictNullTypes option

### ISSUE THREAD

**Issue by fshchudlo** [horiuchi/dtsgenerator#329]
Hello.
Is it possible to add `strictNullTypes` option to generate source files friendly to typescript [strictNullCheck option](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html) instead of optional properties? This would be really useful for projects which uses this typescript option.

**Comment by horiuchi** [comment]
Thank you for using the dtsgenerater.

I know the `strictNullTypes` option.
Do you expect the option of this project.
I think the dtsgeneraters output is added the undefind and null type when non required or added to type property.

**Comment by fshchudlo** [comment]
Now dtsgenerator generates optional property if field is not required:
`interface A {
    fieldA?: string;
}`

It will be great to add `strictNullTypes` option which leads to output below:
`interface A {
    fieldA: string | null;
}`

I think there's no need to add `undefined` as possible value since it's specific to javascript world and has no differences with optional field - both means "nothing". But `null` can be treated as meaningful domain value.

**Comment by horiuchi** [comment]
In the TypeScript world, an optional parameter is treated as `undefined` type.
For example,
https://www.typescriptlang.org/play/index.html#src=function%20f(x%3F%3A%20number)%3A%20void%20%7B%0D%0A%20%20%20%20console.log(typeof%20x)%3B%20%20%2F%2F%20output%20'undefined'%0D%0A%7D%0D%0Af()%3B%0D%0A

Please one more read this document.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html

**Comment by fshchudlo** [comment]
> In the TypeScript world, an optional parameter is treated as undefined type.
@horiuchi I totally agree with you. The same I wrote in message earlier.
But how this resolves the issue? The option to generate code which is friendly to `strictNullCheck` option is still valuable.
