### ISSUE TITLE
Custom namespace removes Paths section

### ISSUE THREAD

**Issue by bori87** [horiuchi/dtsgenerator#331]

**Comment by anttiviljami** [comment]
This strange issue seen in this snapshot.  https://github.com/horiuchi/dtsgenerator/blob/master/test/snapshots/openapi-v3/petstore-change-namespace/_expected.d.ts

**Comment by paxperscientiam** [comment]
Can confirm. Still a problem.

As a workaround, you could probably get what you want out of a name converter function. You'd still want to leave `namespaceName` unset.
EG:
```typescript
function typeNameConvertor(id: SchemaId): string[] {
    const names = DefaultTypeNameConvertor(id);
    console.dir(names)
    if (names.length > 0) {
        const lastIndex = names.length - 1;
        names[lastIndex] = 'I' + names[lastIndex];

        if (names[0] === "Components"){
            names[0] = "NationalWeatherServicePublicDataAPI"
        }
    }
    return names;
}
```

**Comment by horiuchi** [comment]
Please use the `@dtsgenerator/replace-namespace` plugin on v3!
