### ISSUE TITLE
Support for actual enums

### ISSUE THREAD

**Issue by moltar** [horiuchi/dtsgenerator#335]
Would be great to be able to generate actual enums.

Right now, we get:

```ts
interface Foo {
  status: 'ended' | 'active' | 'paused';
}
```

But would be awesome to get:

```ts
enum FooStatus {
  'ended' = 'ended',
  'active' = 'active',
  'paused' = 'paused',
}

interface Foo {
  status: FooStatus;
}
```

And would be even more awesome, if it was possible to filter it before output, so that it can be (optionally) corrected to:

```ts
enum FooStatus {
  'ENDED' = 'ended',
  'ACTIVE' = 'active',
  'PAUSED' = 'paused',
}
```

Thanks!

**Comment by horiuchi** [comment]
I think we should use the union type instead of the enum type.

Let me know what is a good point about the enum type then the union type.

**Comment by moltar** [comment]
To me enum = constants, while union is basically copy pasting strings.

**Comment by horiuchi** [comment]
Not sure, the literal type can check in compile time.
But the enum type can not check in compile time.

Sample:
https://www.typescriptlang.org/play/#src=enum%20E%20%7B%20A%2C%20B%20%7D%0D%0Atype%20T%20%3D%20'A'%20%7C%20'B'%3B%0D%0A%0D%0Avar%20e%3A%20E%20%3D%20100%3B%0D%0Avar%20t%3A%20T%20%3D%20'C'%3B%0D%0A

**Comment by moltar** [comment]
Right, you need string enums, like in my example:

```ts
enum FooStatus {
  ENDED = 'ended',
  ACTIVE = 'active',
  PAUSED = 'paused',
}
```

**Comment by bori87** [comment]
I agree with @moltar. I really need proper Enums

**Comment by horiuchi** [comment]
Sorry, I don’t need this feature.
Please send PR for it, if you need.

**Comment by swillis12** [comment]
If someone has the time this feature would be awesome. I need to use openapi-generator in the mean-time since enums are supported there. I would come back to this in the future once this is supported since the output in a single .d.ts file is really awesome (if someone knows how to do this with openapi-generator that would be nice too)

**Comment by wilmandx** [comment]
I would like to try to develop this feature. @horiuchi could you help me with two things: How could I run the local examples to validate my modifications  and the unit test in master are not passing, what do I have to do apart from npm install ? thanks for your help

**Comment by horiuchi** [comment]
It is now possible to convert union type to enum type using the plugin's post process.
Please consider it.

**Comment by cilius** [comment]
do you have a coded example ?

**Comment by horiuchi** [comment]
This is a simple plugin: https://github.com/dtsgenerator/single-quote/blob/master/index.ts

**Comment by crizo23** [comment]
I'm tempted to open a new issue, because like others have said, this would so much nicer to use:
```
enum FooStatus {
  ENDED = 'ended',
  ACTIVE = 'active',
  PAUSED = 'paused',
}
```

I'd also be interested in working on a plugin, but I'm not really following the single-quote plugin example. @wilmandx or @cilius did you have any luck with this?
