### ISSUE TITLE
Support for maxItems on tuples

### ISSUE THREAD

**Issue by keean** [horiuchi/dtsgenerator#339]
I have looked at a few different ways to work with json-schema in TypeScript, and dtsgenerator seems to be the closest to what I am looking for, and produces nicely formatted and structured typescript definitions. The issue I have is with tuples, for example:
```json
{
    "$id": "https://example.com/test.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "minItems": 2,
    "maxItems": 2,
    "items": [
        {"type": "number"},
        {"type": "string"}
    ]
}
```
This generates:
```typescript
declare namespace ExampleCom {
    export type TestJson = [number, string] | [number, string, any];
}
```
Which is too permissive, what I really want is:
```typescript
declare namespace ExampleCom {
    export type TestJson = [number, string];
}
```
Could dtsgenerator be extended to support `maxItems` for this use case, or is there another way to achieve what I want?

**Comment by horiuchi** [comment]
Now the dtsgenerator is not supported the `maxItems` property.
All supported properties are described in this document (https://github.com/horiuchi/dtsgenerator/blob/master/SupportedFeatures.md).

But I will consider supporting the `maxItems` property on tuple type.

**Comment by horiuchi** [comment]
@keean Sorry late!
I released the improvement of the tuple type output.
