### ISSUE TITLE
Bug: OpenAPI v3 requestBody and response objects do not support $ref

### ISSUE THREAD

**Issue by anttiviljami** [horiuchi/dtsgenerator#342]
The `searchAllSubSchema` function skips registering schemas for these instances:

```
requestBody:
  $ref: '#/components/requestBodies/MyRequestBody'
```

```
responses:
  200:
    $ref: '#/components/responses/MyRequestBody'
```

The reason is that `setSubIdToRequestBody` and `setSubIdToResponseV3` only proceed to setSubId if the `content` property exists. https://github.com/horiuchi/dtsgenerator/blob/master/src/core/jsonSchema.ts#L270 

Easy fix though. :)

**Comment by horiuchi** [comment]
@anttiviljami Thank you!
Sure, that's my bug.
