### ISSUE TITLE
fix error: The $ref targets root is not found:

### ISSUE THREAD

**Issue by steelydylan** [horiuchi/dtsgenerator#346]
Hi @horiuchi 
Thank you for publishing the new version.
But Since the v2.0.7, I have been facing with the error `The $ref targets root is not found:`
I think it is because of the below commit
https://github.com/horiuchi/dtsgenerator/commit/17a042f14e6e0d0975220f8b0c9dfd770763b587

Please examine :(

**Comment by mribichich** [comment]
i found this problem too. debugging I found out that the lib doesnt add schemes for `components/responses` that dont contain a `content` or `ref` property.

is this the expected behavior?

because we have in our `openapi.yaml` a component like this, without a content or ref property. so later on it throws: `The $ref targets root is not found`

```
    Standard201CreatedResponse:
      description: The object has been created.
      headers:
        Location:
          $ref: '#/components/headers/Location'
        X-RateLimit-Limit:
          $ref: '#/components/headers/X-RateLimit-Limit'
        X-RateLimit-Remaining:
          $ref: '#/components/headers/X-RateLimit-Remaining'
    Standard304NotModifiedResponse:
      description: The object has not been modified.
      headers:
        X-RateLimit-Limit:
          description: The number of allowed requests in the period
          schema:
            type: integer
        X-RateLimit-Remaining:
          description: The number of remaining requests in the period
          schema:
            type: integer
```

**Comment by mribichich** [comment]
for what I see in the openapi spec, content or ref its not required, becuase its ok to define a response that returns empty

reference: http://spec.openapis.org/oas/v3.0.2#response-object

![image](https://user-images.githubusercontent.com/5748554/59230549-2acd9100-8bb4-11e9-9b87-03a9c3a7b6de.png)

![image](https://user-images.githubusercontent.com/5748554/59230565-36b95300-8bb4-11e9-8a81-89b531c6d9e2.png)

I could send a PR

**Comment by horiuchi** [comment]
@mribichich Thank you for your investigation!
But the below schema doesn't occur the error.

Please repro schema.

```
openapi: "3.0.2"
info:
  title: empty response
  version: v0.1
components:
  schemas:
    object:
      type: object
      properties:
        id:
          type: string
  responses:
    created:
      description: 'object created'
paths:
  post:
    requestBody:
      application/json:
        $ref: '#/components/schemas/object'
    responses:
      204:
        $ref: '#/components/responses/created'
```

**Comment by breathe** [comment]
This swagger.json file (for statuspage.io api) also encounters above issue

https://developer.statuspage.io/bc92ff94-0e03-4977-917c-2211fca79018

**Comment by horiuchi** [comment]
@breathe I found the reason for that schema error.

The `dtsgenerator` is not supported the `application/x-www-form-urlencoded` branch now.
via. https://github.com/horiuchi/dtsgenerator/blob/master/SupportedFeatures.md#version-30

**Comment by horiuchi** [comment]
I supported the `application/x-www-form-urlencoded` branch by v2.1.0.

**Comment by adriengibrat** [comment]
Just letting a trail here in case others are looking for the "The $ref targets root is not found" error:

The PR https://github.com/horiuchi/dtsgenerator/pull/371 is my attempt to fix some errors related to the use of 'responses' & 'requestBodies'  components.
