### ISSUE TITLE
Example of how to use

### ISSUE THREAD

**Issue by fantapop** [horiuchi/dtsgenerator#347]
Typescript newbie here. I'm having a heck of a time figuring out how to use the definition file which is output by this library.

I've placed the generated d.ts file into a directory under src/ like so:

./src/generated/types/api.d.ts

When I try to pull types out of it in my code however I'm getting an error:
```
// error: File '....../src/js/generated/types/api.d.ts' is not a module.ts(2306)
import { Report } from 'generated/types/api';
```

Indeed there are no modules declared in the definitions file only namespaces.  How can I use these types?

**Comment by fantapop** [comment]
I was able to get this working like so which I think is the ambient declaration way.
```
import 'generated/types/api';
```

Is there a way to have this use modules instead?

**Comment by fantapop** [comment]
Actually, I'm still having trouble here.  I've generated the types with no namespace as specified in the README using `-n "" to suppress namespaces.`.  However none of the interfaces are being exported now.  end up with output like this:

```
/**
 * DayDimensionData
 */
declare interface DayDimensionData {
    /**
     * Key
     */
    key: "day";
    /**
     * Values
     */
    values: string /* date */ [];
    /**
     * Valuetype
     */
    valueType: "day";
}
```

All the interfaces are `declare`d instead of `export`  If I manually changes them to be `export` I can use them successfully.  Am I doing something wrong?

**Comment by fantapop** [comment]
Okay, I was able to get this working using namespaces.  I don't really understand how the no namespaces option is helpful since nothing is exported.  For other noobs, build with a namespace:
`yarn dtsgen -n "MyNamespace" -o src/js/types/generated/my-types.ts swagger.json`
then in your code:
```
import 'types/generated/my-types';

const myVar: MyNamespace.AwesomeType = {};
```

**Comment by Overtorment** [comment]
that worked for me:

```
dtsgen   openapi.yaml  > src/openapi/api.ts
```

```
import '../openapi/api';

const myVar: Components.Schemas.ServerInfo = {};
```
