### ISSUE TITLE
Export as module instead of namespace

### ISSUE THREAD

**Issue by piero-b** [horiuchi/dtsgenerator#349]
Is it possible to generate the typing file in the following way?

1. No namespaces as Angular now advises against these for modules instead

1. Types can be exported as classes instead of interfaces

1. Paths are not exported

**Comment by kierson** [comment]
This also helps to use such definitions in setup babel7 + typescript.
In such setup namespaces are not supported.

**Comment by horiuchi** [comment]
Hm, the `module` and the `namespace` is different.
https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html

And the dtsgenerator generate the type declare file only, not included runtime value.
Then the babel can compile the generated files.
https://github.com/babel/babel/issues/8244#issuecomment-419979558

**Comment by kierson** [comment]
Hmm I've read babel docs a few weeks ago and namespaces were not supported yet.
So my comment is invalid then. I will try again with your generator.
