### ISSUE TITLE
Possible to Authenticate to remote server for downloading schema?

### ISSUE THREAD

**Issue by swillis12** [horiuchi/dtsgenerator#355]
I see the "--url" option, but am not sure how I can use this when my server requires authentication to access the schema. Has anyone else has had this issue or do you use the tool in a different way so that this is not a problem?

**Comment by horiuchi** [comment]
Would you use below command?
```
curl 'URL' | dtsgen
```

**Comment by swillis12** [comment]
Thanks @horiuchi, I will script around curl to achieve this. I thought I would check since some gen libraries have 'headers' options
