### ISSUE TITLE
Add Dynamic Media Types

### ISSUE THREAD

**Issue by buelsenfrucht** [horiuchi/dtsgenerator#363]
Hi folks,

according to JSON Schema Draft-07 it is allowed to use placeholders within media types, e.g. "application/problem+json", see [draft](https://json-schema.org/draft-07/json-schema-release-notes.html#instance-media-type).

It would be great if this would be supported by this generator.

**Comment by horiuchi** [comment]
What do you mean?
The media type is not referenced when the `dtsgenerator` gets the schema via URL.

**Comment by buelsenfrucht** [comment]
With commit 'ff569d1' you introduced media type "application/x-www-form-urlencoded" next to "application/json". But Type application/json can have additional infos such as "application/problem+json".

For example our responses look like this:

```
{
  "components": {
    "responses": {
      "BadRequest": {
        "content": {
          "application/problem+json": {
            "schema": {
              "$ref": "#/components/schemas/API.Error"
            }
          }
        },
        "description": "Bad Request",
        "headers": {
          "X-Request-ID": {
            "description": "Unique Request ID",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}
```

This should be valid but doesn't work with the dtsgenerator as long as I don't change the type to "application/json".

**Comment by horiuchi** [comment]
Oh, I understand.
That's for OpenAPI spec's schema.

OK, I will add to support the `application/*+json` media type.

**Comment by horiuchi** [comment]
Released!

**Comment by buelsenfrucht** [comment]
Great, thanks a lot!
