### ISSUE TITLE
output for --namespace combined with wildcard omits all but last input file

### ISSUE THREAD

**Issue by DavidBiesack** [horiuchi/dtsgenerator#369]
When using 
```
dtsgen --namespace "Sample" --out gen/types.d.ts gen/schemas/*.json
```
(where `gen/schemas` contains `a.json`, `b.json`, `c.json`)
the output contains only the type definition for c.

Omit `--namespace "Sample"` and the command works, generating types for a, b, and c.

**Comment by horiuchi** [comment]
Please show the repro schemas.

Would your type names be same?
If so, the custom namespace feature overrides the same name types.

**Comment by DavidBiesack** [comment]
I've attached some sample schemas.

I see what is happening - without `--namespace`,  dtsgen is using the `"id"` in the schema to create a set of nested namespaces, so  each schema gets a unique namespace because each schema has a unique `"id"`. 

```
$ dtsgen gen/schemas/*.json && cat types.d.ts
declare namespace ApiApitureCom {
    namespace Schemas {
        namespace Test {
            namespace A {
                namespace V100 {
                    /**
                     * Schema a
                     */
                    export interface SchemaJson {
                        /**
                         * Field a
                         */
                        a?: string;
                    }
                }
            }
            namespace B {
                namespace V100 {
                    /**
                     * Schema b
                     */
                    export interface SchemaJson {
                        /**
                         * Field b
                         */
                        b?: string;
                    }
                }
            }
            namespace C {
                namespace V100 {
                    /**
                     * Schema c
                     */
                    export interface SchemaJson {
                        /**
                         * Field c
                         */
                        c?: string;
                    }
                }
            }
        }
    }
}
```
When using `--namespace Sample", dtsgen defines the `interface` based only on the _last path element_ from the `"id"`. In my case, all the schemas use a pattern that puts the unique name in the middle of the path, such as 
```
"id": "https://api.apiture.com/schemas/test/a/v1.0.0/schema.json"
```
and thus all end up with the name "JsonSchema" and hence each file overwrites the previous - 
```
$ dtsgen -n Sample gen/schemas/*.json
declare namespace Sample {
    /**
     * Schema c
     */
    export interface SchemaJson {
        /**
         * Field c
         */
        c?: string;
    }
}
```
I prefer to use my "id" pattern, but in order for dtsgen to work, I may need to change my schemas
so the last element is not "schema.json" but is just "a", "b", "c"... unless there was some other way to define what interface name to use for each schema?

[schemas.zip](https://github.com/horiuchi/dtsgenerator/files/3652935/schemas.zip)

**Comment by horiuchi** [comment]
In the `@dtsgenerator/replace-namespace` plugin You can now configure the replacement namespace in more detail. We recommend you use it.
