### ISSUE TITLE
Error: The $ref targets root is not found

### ISSUE THREAD

**Issue by mbohgard** [horiuchi/dtsgenerator#370]
When running dtsgenerator on the following OpenAPI 3 spec I get the error `Error: The $ref targets root is not found: #/components/platform/schemas/Nope`
```yaml
openapi: 3.0.0
info:
  version: "0.2"
  title: test
paths:
  /test:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/platform/schemas/Nope"
components:
  schemas:
    Response:
      type: object
      properties:
        type: array
        items:
          type: string
  platform:
    schemas:
      Nope:
        type: object
        required:
          - type
        properties:
          type:
            type: string
```

How come? Looks perfectly valid to me? `#/components/schemas/Response` is resolved correctly.

**Comment by horiuchi** [comment]
The `components/platform/` path is not supported by the dtsgenerator.
Because that path is not defined by the OpenAPI spec. via. http://spec.openapis.org/oas/v3.0.2#components-object

**Comment by mbohgard** [comment]
@horiuchi You're right, it's not supported. I had to use [Speccy](https://github.com/wework/speccy) to combine OpenAPI specs to one big file because dtsgenerator doesn't support `$ref` to other files, right?
```yaml
components:
  schemas:
    $ref: ./schemas.yaml
```
...will also result in `$ref targets root is not found`.

**Comment by mbohgard** [comment]
@horiuchi By the way, I'm confused. In the spec [over here](https://swagger.io/docs/specification/components/) it says components can have a bunch of different properties. What gives?

**Comment by horiuchi** [comment]
It supports the other file reference.
An example is here: https://github.com/horiuchi/dtsgenerator/blob/master/test/snapshots/json-schema-draft-07/simple-example/simple_example.json#L40

This implementation is our own interpretation of [JSON Reference](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03) and [JSON Pointer](https://tools.ietf.org/html/rfc6901).

**Comment by mbohgard** [comment]
Ok, so dtsgenerator doesn't really support OpenAPI 3 or how are all these specs dependant on each other? Like I said, I'm confused...

**Comment by horiuchi** [comment]
Yes, the dtsgenerator doesn't support all OpenAPI specs yet.
Please see the document: https://github.com/horiuchi/dtsgenerator/blob/master/SupportedFeatures.md#openapi

**Comment by mbohgard** [comment]
Ok thank you, that clears it up. Thank you for your work on dtsgenerator. <3
