### ISSUE TITLE
Usage of Dtos with Babel

### ISSUE THREAD

**Issue by Christian24** [horiuchi/dtsgenerator#377]
Hi,

we stumbled upon the following problem today. We are currently importing our DTOs like so: 
````typescript
import DeleteAccountBadRequestResponseDTO = Definitions.DeleteAccountBadRequestResponseDTO;
````

However, this does not work with Babel: https://github.com/babel/babel/issues/7067. So, I am a bit unsure what is a good way to resolve this:
* maybe there is a different way to import?
* maybe the namespace could be replaced with a module named the name of the namespace? 
````typescript 
import {DeleteAccountBadRequestResponseDTO} from '../../generated/definitions';
````
This would of course only be an opt in flag for generation. 

What do you think is the best way to resolve this?

**Comment by horiuchi** [comment]
In such a case, the following notation is sufficient.

```
type DeleteAccountBadRequestResponseDTO = Definitions.DeleteAccountBadRequestResponseDTO;
```

**Comment by Christian24** [comment]
Any chance these type declarations  would be generated and exported by dtsgenerator in the future? I think it would be a bit tedious to reexport types already generated by the tool just to make babel happy.

**Comment by horiuchi** [comment]
I'm sorry I don't understand what is the problem.

What do you trying to import?
If you need support, it would be helpful to have a minimum reproduction file.

**Comment by Christian24** [comment]
I will try my best how we (me and my coworker) got here:

We are using dtsgenerator in a larger project. So we have a lot of DTOs. Our generated code looks something like this (pseudo code):
````typescript
declare namespace Definitions {
export interface ADTO {
//Something in here
}
export interface BDTO {
// Some more in here
}
// lots more interfaces

}
````
In code we use it like this:
````typescript
// Webstorm does this for us automatically
import ADTO = Definitions.ADTO;
const response: Response = await fetch(url, options);
const data: ADTO = await response.json();
````
This worked okay for us in the past. However, Babel does not understand that import syntax. 
Now what we could do as you said is this: 
````typescript
type ADTO = Definitions.ADTO;
const response: Response = await fetch(url, options);
const data: ADTO = await response.json();
````
This would work, but we would be defining a type while in reality we would want to import the interface `ADTO` that already exists. We would have to do this for a lot of interfaces, so eventually we would reexport/redefine everything in the namespace. 

Another idea would be to just do: 
````typescript
const response: Response = await fetch(url, options);
const data: Definitions.ADTO = await response.json();
````
However, this is not so readable I think. Another thing is my coworker did mention he finds the ambient namespace to be a little bit of "magic" as this is the only place we were constantly using a namespace, but it is generated for us. 

What I could imagine as a solution is offering an option to output a module, not a namespace. So instead of the namespace we would have as output from dtsgenerator:
````typescript
//definitions.d.ts
export interface ADTO {
//Something in here
}
export interface BDTO {
// Some more in here
}
// lots more interfaces

````
In our code we could use it just like every other module:
````typescript
// Webstorm does this for us automatically
import {ADTO} = '../generated/definitions.d';
const response: Response = await fetch(url, options);
const data: ADTO = await response.json();
````

This would be closer to JavaScript modules, would be supported by tooling and easy to understand. Alternatively could also generate a second file which would just look like this:
````typescript
//definitions.d.ts
export type ADTO = Definitions.ADTO;
export type BDTO = Definitions.BDTO;
// lots more types

````
It is just an idea for now, but I hope it explains where we are coming from and where we hope to go.

**Comment by Christian24** [comment]
@horiuchi what do you think? I think I am in favor of the output modules idea. Maybe after my vacation I could try to implement this. If you are okay with it of course.

**Comment by horiuchi** [comment]
@Christian24  If do you want to reduce or remove namespace only, please try to use the `--namespace` option.
This option converts root namespace.

**Comment by duhseekoh** [comment]
Namespaces are basically deprecated. New projects don't use them. It's a legacy pattern left in typescript from when es6 modules were not as widely adopted as they are now. 
Ideally this package could output multiple ts file that use the es6 module system (import/export) and remove all references to namespaces.

**Comment by Christian24** [comment]
@horiuchi sorry, for the late response, I was on vacation and then had to catch up with everyday stuff. If I do `--namespace ''` it does not generate a root namespace named `_`:
````typescript
declare namespace _ {
}
```` 
I do agree with @duhseekoh: Outputting multiple files that use the es6 module system should be the way to go. It does not have to be the default if you want to keep supporting namespaces, but it should at least be an option.

**Comment by horiuchi** [comment]
In the `@dtsgenerator/replace-namespace` plugin You can now configure the replacement namespace in more detail.
We recommend you use it.

**Comment by Christian24** [comment]
@horiuchi Thanks, I will check it out. Does it allow to disable namespace generation though? Since Babel does not support namespaces. 

I saw there is now a plugin system. If I find the time I might be able to put something together otherwise.

**Comment by horiuchi** [comment]
Using the `@dtsgenerator/replace-namespace` plugin You can remove all namespaces.
However, this is not expected to work in all cases because of concerns about the uniqueness of the type name.

So it would be nice to have a post-hook plugin for OpenAPI v3 that converts the type names to be unique instead of using a namespace.

**Comment by Christian24** [comment]
@horiuchi sorry, I was pretty busy, so I am only coming back to this now. 

I haven't really figured out how I would need to configure the `@dtsgenerator/replace-namespace` plugin. 

My naive solution to this problem would be as follows: 
For every OpenAPI schema create a new folder, so `schema.json` would create a new folder `schema`. For every type create a new snake case file. So, for the type `GetUserResponseDTO`, the file name containing that definition would be `get-user-response-dto.d.ts`. If the type `GetUserResponseDTO` also exists in a schema `schemaB.json`, it would end up in the folder `schemaB`, so there should be no collision. 

As said this is is just my naive solution, I haven't tested it. I looked at creating my own plugin to make this work, but hit a few road blocks along the way for which I opened issues at https://github.com/dtsgenerator/create. 

In addition there seems to be no `process` hook right? Is the file already in the process of being written in `postProcess` hook? 

Also, on a bit of a different note: Is there any good documentation for the typescript compiler API or is https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API as good as it gets?  

Looking forward to hearing your thoughts. :)

**Comment by horiuchi** [comment]
> For every OpenAPI schema create a new folder, so schema.json would create a new folder schema. For every type create a new snake case file. So, for the type GetUserResponseDTO, the file name containing that definition would be get-user-response-dto.d.ts. If the type GetUserResponseDTO also exists in a schema schemaB.json, it would end up in the folder schemaB, so there should be no collision.

The types must be unique at compile time. 
Even if the files are separate, you'll get an error if you reference the same name type from a program. However, if you don't have to worry about that, I don't think it's a problem.

> As said this is is just my naive solution, I haven't tested it. I looked at creating my own plugin to make this work, but hit a few road blocks along the way for which I opened issues at https://github.com/dtsgenerator/create.
> 
> In addition there seems to be no process hook right? Is the file already in the process of being written in postProcess hook?

The scaffolded plugins have no hooks at all, so I'm assuming the author will add a pre-hook or post-hook.
You can add either pre-hook, post-hook, or both.

> Also, on a bit of a different note: Is there any good documentation for the typescript compiler API or is https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API as good as it gets?

Yes, I used that page as a reference myself.
Other than that, I also found deep dive to be helpful, although it's a bit old.
https://basarat.gitbook.io/typescript/overview

**Comment by horiuchi** [comment]
As for solutions, I think it's best to go back to the beginning and sort out what you want and need to do.

**Comment by Christian24** [comment]
> > For every OpenAPI schema create a new folder, so schema.json would create a new folder schema. For every type create a new snake case file. So, for the type GetUserResponseDTO, the file name containing that definition would be get-user-response-dto.d.ts. If the type GetUserResponseDTO also exists in a schema schemaB.json, it would end up in the folder schemaB, so there should be no collision.
> 
> The types must be unique at compile time.
> Even if the files are separate, you'll get an error if you reference the same name type from a program. However, if you don't have to worry about that, I don't think it's a problem.
> 

I think that is not really a problem, since it only applies if you have two identical imports in one file. 
> > As said this is is just my naive solution, I haven't tested it. I looked at creating my own plugin to make this work, but hit a few road blocks along the way for which I opened issues at https://github.com/dtsgenerator/create.
> > In addition there seems to be no process hook right? Is the file already in the process of being written in postProcess hook?
> 
> The scaffolded plugins have no hooks at all, so I'm assuming the author will add a pre-hook or post-hook.
> You can add either pre-hook, post-hook, or both.
> 

I guess I would use a post process hook. I am trying to parse the Typescript source file, it sounds very easy, just extracting everything inside the namespaces. However, I am hitting a road block as I fail to extract those. The nodes all seem to be unparsed sources. Any idea what is up here?

I published my code here: https://github.com/Christian24/multi-file

If I manage to finish it, I would love to donate it back to the dtsgenerator umbrella, so everyone can use it. 

> > Also, on a bit of a different note: Is there any good documentation for the typescript compiler API or is https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API as good as it gets?
> 
> Yes, I used that page as a reference myself.
> Other than that, I also found deep dive to be helpful, although it's a bit old.
> https://basarat.gitbook.io/typescript/overview

This looks helpful, to see the generated source file: https://ts-ast-viewer.com/#
And this seems like a great abstraction over the API:
https://github.com/dsherret/ts-morph/tree/latest/packages/ts-morph

**Comment by horiuchi** [comment]
> I guess I would use a post process hook. I am trying to parse the Typescript source file, it sounds very easy, just extracting everything inside the namespaces. However, I am hitting a road block as I fail to extract those. The nodes all seem to be unparsed sources. Any idea what is up here?

The post-process is for converting AST, and the return value of the `ts. SourceFile` type is output as the result of the command. As a result, the post-process does not allow for file splitting.
But, you may be able to do what you want to do by using the pre-process to filter out only the parts of the incoming schema that you need for each file. Of course, you can also split the input schema by other means, without using a plugin.

**Comment by horiuchi** [comment]
And you might want to take a look at my plugin for an example of post-process.

example1 (so simple): https://github.com/dtsgenerator/single-quote/blob/master/index.ts#L35
example2: https://github.com/dtsgenerator/decorate-typename/blob/master/index.ts#L71
