### ISSUE TITLE
regression in 2.4.0

### ISSUE THREAD

**Issue by Oloompa** [horiuchi/dtsgenerator#391]
Hi i updated to last version (2.4.0)

i use following command `dtsgen --out out/schema.d.ts in/schema.json`

Previously it gave me something like `schema.d.ts`
```typescript
declare interface Something {
    foo: string;
}
```

Now i got `schema.d.ts`
```typescript
export interface Something {
    foo: string;
}
```

My definitions are not loaded automatically anymore. It broke both IDE and transpilation

**Comment by horiuchi** [comment]
@Oloompa Please show the repro schema file.

Probably, It's related to this PR( #386 ).

**Comment by Oloompa** [comment]
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "something",
    "type": "object",
    "properties": {
        "foo": { "type": "string" }
    },
    "additionalProperties": false,
    "required": ["foo"]
}

**Comment by horiuchi** [comment]
Oh, I repro this issue. That's a bug.
I will fix it soon.

**Comment by horiuchi** [comment]
@Oloompa I released the fixed version.
Thank you for your reporting! 👍

**Comment by Oloompa** [comment]
I confirm the fix
