### ISSUE TITLE
only supports application/json media type

### ISSUE THREAD

**Issue by silesky** [horiuchi/dtsgenerator#395]
```
"paths": {
   "/v2/hello": {
      "get": {
        "responses": {
          "200": {
            "$ref": "#/components/responses/GetHelloV2"
          }
        }
      }
    },
},
"responses": {
  "GetHelloV2": {
        "description": "Successfully returned a greeting.",
        "content": {
          "text/plain": { // this does not work
            "schema": {
              "type": "string",
              "example": "Sup!"
            }
          }
        }
      },
}
```

I would expect GetHelloV2 to come back type "string"

**Comment by horiuchi** [comment]
@silesky now it supported media types are bellows only. The `text/plain` is not supported yet.
https://github.com/horiuchi/dtsgenerator/blob/master/SupportedFeatures.md#support-media-type

**Comment by silesky** [comment]
@horiuchi is there an interest in a PR?

**Comment by horiuchi** [comment]
Yes, if you take a PR I will merge it 😄

**Comment by silesky** [comment]
@horiuchi  -- question: is there  a reason we aren't using https://www.npmjs.com/package/json-schema-ref-parser ?

**Comment by silesky** [comment]
PR here: https://github.com/horiuchi/dtsgenerator/pull/396/files

**Comment by horiuchi** [comment]
#396 is merged!
