### ISSUE TITLE
request for enum sorting support

### ISSUE THREAD

**Issue by KostblLb** [horiuchi/dtsgenerator#397]
we've stumbled across a swagger issue that it generates string enum arrays in random order, i.e. we can have something like `{ type: 'string', enum: [ 'Foo', 'Bar'] }`, and then relaunch our web server and get `{ type: 'string', enum: [ 'Bar', 'Foo'] }`. in our CI pipeline we verify swagger.json agains previously generated versions, so this causes false alarms.
can you introduce some options for forced ordering of string enums? 
or maybe, for better flexibility, options to provide a child class of SchemaConvertor to dtsgenerator?

**Comment by horiuchi** [comment]
The `dtsgenerator` is implemented as referential transparency. That is, it returns the same output for the same input. In this case, because the input is different, it is better to fix the input data.
So on the next version, I will implement the plugin feature. As a plug-in, I think it would be nice to add a sorting function.

**Comment by KostblLb** [comment]
Plugin sounds cool :D

**Comment by rcidaleassumpo** [comment]
@horiuchi isn't just easier for @KostblLb to just run a script after the .json is generator and do the sorting ? I don't understand

```import dtsGenerator, { DefaultTypeNameConvertor, SchemaId } from 'dtsgenerator';
import * as fs from 'fs';

const filePath = '../../test/snapshots/json-schema-draft-04/schema/schema.json';

function typeNameConvertor(id: SchemaId): string[] {
    const names = DefaultTypeNameConvertor(id);
    if (names.length > 0) {
        const lastIndex = names.length - 1;
        names[lastIndex] = 'I' + names[lastIndex];
    }
    return names;
}

async function main(): Promise<void> {
    const content = JSON.parse( fs.readFileSync(filePath, 'utf-8') );
    const result = await dtsGenerator({
        contents: [content],
        typeNameConvertor,
    });
    console.log(result);
}
main();
```

@KostblLb Can't you just use that and instead of adding I to your interface names, do the same for the result of the enums, and sort them ?

**Comment by KostblLb** [comment]
@rcidaleassumpo, sorry, but i don't get how this example can be modified to sort enum values. isn't typeNameConvertor supposed to only update type names, and not property values?

**Comment by rcidaleassumpo** [comment]
@KostblLb the example shows how you can interact with the tools. Then you find your way into fixing your issue, because is really specific to "your" problem.

**Comment by KostblLb** [comment]
@rcidaleassumpo well the idea of plugins is that you write your own code for "your" problems, and I'm happy that @horiuchi supports the idea of adding plugins to dtsgenerator. The advice to "find my own way into fixing my issue" just sounds as i have to write my own d.ts generator, thank you

**Comment by horiuchi** [comment]
It is now possible to convert the enum type values using the plugin's post process.
Please consider it.
