### ISSUE TITLE
Dollar sign role in the name of an endpoint namespace

### ISSUE THREAD

**Issue by unclechu** [horiuchi/dtsgenerator#402]
What's dollar sign in the name of an endpoint namespace for?

For instance `/search/{query}` becomes `Search$Query` so I assumed it always precedes any placeholder name.

But `/test6/foo/{bar}/baz/bzz/{zzz}/aaa` becomes `Test6Foo$BarBazBzzZzzAaa`, only `Bar` is preceded with a dollar sign but not `Zzz`, is it intended to be like that? Why only the first placeholder name has dollar sign in front of it?

**Comment by horiuchi** [comment]
@unclechu Thank you for your bug report! 👍 
This issue is a bug.
