### ISSUE TITLE
please fix example

### ISSUE THREAD

**Issue by maapteh** [horiuchi/dtsgenerator#421]
https://github.com/horiuchi/dtsgenerator/blob/master/example/add-prefix/index.ts

your new version broke your only example :)

**Comment by horiuchi** [comment]
@maapteh Oh, Thank you for your report!
We don't need that example anymore, so I'm going to delete it.

**Comment by maapteh** [comment]
But it would be nice for people moving from versions. We had the node script running to wrap everthing with the option you now moved to the plugin. But to understand how this will now work cant be done in seconds, you need to go trough all stuff :)
