### ISSUE TITLE
Config file could not be loaded

### ISSUE THREAD

**Issue by Christian24** [horiuchi/dtsgenerator#423]
Hello,

I just tried to update to dtsgen 3.0.1. Sadly I always get an error when trying to generate dtos: `Error to load config file from dtsgen.json`. 

A few things to note: 
* I wouldn't need a configuration file for what I want to do, it is surprising `dtsgen` is still looking for it. 
* I tried to create a stub file, because I do not need any plugins, but it seems it cannot even find that file. Maybe it tries to load it from `node_modules/dtsgenerator/bin`? 

When I come home I will try to investigate further.

Thanks,
Christian

**Comment by tfrcm** [comment]
same

**Comment by horiuchi** [comment]
If a configuration file is not needed, the error is no longer displayed.
