### ISSUE TITLE
Cannot load config file

### ISSUE THREAD

**Issue by DamianOsipiuk** [horiuchi/dtsgenerator#428]
I tried to use the config file when this package was installed locally with no luck.
- directly from bash
```
./node_modules/.bin/dtsgen -c dtsgen.json --out ./types.d.ts "--info"
Error to load config file from dtsgen.json
Version: 3.1.0
ConfigFile: undefined

Config:
  input:
    stdin: true
  outputFile: "./types.d.ts"
  target: ESNext
  plugins:

Plugins: count=0
```
Same for `./dtsgen.json` and no config specified, which should default to the same name.

The same issue happens when using this lib from npm script
```
npm run typegen
> dtsgen -c dtsgen.json --out types.d.ts --info

Error to load config file from dtsgen.json
Version: 3.1.0
ConfigFile: undefined

Config:
  input:
    stdin: true
  outputFile: "types.d.ts"
  target: ESNext
  plugins:

Plugins: count=0
```

The same thing happens when installed globally.

`pwd` command shows the correct working directory.

When I specify the full path to the config file it works:
```
./node_modules/.bin/dtsgen -c ~/test/dtsgen.json --out ./types.d.ts --info
Version: 3.1.0
ConfigFile: /home/mrmentor/test/dtsgen.json

Config:
  input:
    stdin: true
  outputFile: "./types.d.ts"
  target: ESNext
  plugins:
    @dtsgenerator/replace-namespace: {"map":[{"from":[true],"to":["asdf"]}]}

Plugins: count=1
  @dtsgenerator/replace-namespace@1.3.1: replace the namespace names
```

Anything i have missed or the file resolution is not working properly?

**Comment by horiuchi** [comment]
type `. /dtsgen.json` if you want to read the files in the current directory.

**Comment by DamianOsipiuk** [comment]
Not sure if the space in your example is deliberate, but I feel it won't work as a parameter.

If you meant `./dtsgen.json` then I have also tried that as mentioned in the issue description.

**Comment by horiuchi** [comment]
@DamianOsipiuk Oh sorry, that's a bug.
It seems that the relative path was not loading properly.

**Comment by horiuchi** [comment]
Released the bug fixed version.
