### ISSUE TITLE
Programmatic interface (NodeJS API)

### ISSUE THREAD

**Issue by nfroidure** [horiuchi/dtsgenerator#432]
Do you think it could be feasible to export a programmatic interface so that we could use it in actual code without spawning a new process?

This is very common to do so (see webpack, eslint...).

**Comment by horiuchi** [comment]
I think that feature can be achieved with a plugin system.

What exactly do you want to do? Please let me know if there are any features missing from the current plugin.

**Comment by nfroidure** [comment]
I want to use this tool in an existing script (not via the CLI), in order to generate the types whenever the OpenAPI changes when in dev mode (maybe via a webpack plugin, not sure yet) for [this project](https://github.com/nfroidure/whook/issues/51). I could do so by spawning a new process to execute the CLI (and probably will in the meanwhile), but I think it would be better to do it via a NodeJS API interface.

By walking through the source, I think I could use the code via the `DtsGenerator` class, but I would have no guarantee of a stable interface since it is not an official feature of this module.

**Comment by horiuchi** [comment]
I see. I don't think there's anything wrong with using the NodeJS API for that purpose.

See the `src/cli.ts` for more information: https://github.com/horiuchi/dtsgenerator/blob/master/src/cli.ts#L96
At least until the major version changes, the dtsgenerator interface should remain unchanged. However, there may be some additions and changes to the Config module.
