### ISSUE TITLE
Support `patternProperties`

### ISSUE THREAD

**Issue by nfroidure** [horiuchi/dtsgenerator#435]
With the coming OAS 3.1 specs, JSON Schema pattern properties will be supported (and in general all JSON Schema features) : 
https://www.openapis.org/blog/2020/06/18/openapi-3-1-0-rc0-its-here

I strongly rely on pattern properties and would like to see it the soonest possible in this package I rely on. I'm open for proposing a patch in that way but would like you to confirm any interest on it before.

Note for myelf: things should happen here (correct me if I'm wrong ;) ) : https://github.com/horiuchi/dtsgenerator/blob/master/src/core/dtsGenerator.ts#L242-L259

**Comment by horiuchi** [comment]
@nfroidure Thank you for your information.

I need to support the new JSON Schema draft of the `2019-09` version.
The new draft adds a new specification in addition to clarifying the $ref solution, so it's going to be a bit of a challenge to keep up.

**Comment by nfroidure** [comment]
Afaik, the `patternProperties` is part of the JSON Schema specs since a while so I think it could be done before:
https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#section-6.5.5

I'll give it a quick try, I need this anyway so forked for my own needs. I'll propose a PR whenever I succeed.

**Comment by nfroidure** [comment]
Here we go:
https://github.com/horiuchi/dtsgenerator/pull/436

Having several index properties causes issues : https://ts-ast-viewer.com/#code/KYDwDg9gTgLgBDAnmYcAyEA2cC8cDeAUHCXANqZYBccAzjFAJYB2A5gLo31NsDcxpClgBMXBiw5ierfgF9CQA

So I grouped the various `patternProperties` to a single `pattern` index property containing a union type of all the posible pattern properties.

It could be once possible to split it into several indexed properties with the following proposal : https://github.com/Microsoft/TypeScript/issues/6579

LMKWYT ;)

**Comment by horiuchi** [comment]
@nfroidure Thank you for your information!
When that proposal is merged, we'll be able to type them properly.

**Comment by nfroidure** [comment]
@horiuchi thank you for such quick answers and thanks for this great module, have a nice day !
