### ISSUE TITLE
oneOf produces linked list instead of union type

### ISSUE THREAD

**Issue by ArtemeeSenin** [horiuchi/dtsgenerator#442]
Hello, thank you for your work!

I have an issue with getting not TS union type for `oneOf` in swagger docs

This is example of input for `GeneralItem` which I suppose should be a union type like `export type GeneralItem = Entity | Section`

```yaml
GeneralItem:
      oneOf:
      - $ref: '#/components/schemas/Entity'
      - $ref: '#/components/schemas/Section'
    Entity:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Section:
      required:
      - id
      - name
      - children
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        children:
          $ref: '#/components/schemas/ListOfItems'
```

Here is the result in generated file:

```ts
export interface GeneralItem {
        head: GeneralItem;
        next: ListGeneralItem;
    }

export type ListGeneralItem = GeneralItem | Nil;
```

And therefore I can't get the real contents of GeneralItem

**Comment by ArtemeeSenin** [comment]
I don't know this codebase but have seen your [fix for object types](https://github.com/horiuchi/dtsgenerator/pull/352/files#diff-55ce0c9325fb57ed8d69376623d23ac4R84) maybe deletion of the type prop in contents object causes this issue, not shure

**Comment by horiuchi** [comment]
Please try Version 3.6.0.
If you still have problems, please reopen it.
