### ISSUE TITLE
Operations without response body gets `{}` as their `responses.$200` type

### ISSUE THREAD

**Issue by henhal** [horiuchi/dtsgenerator#445]
If an operation has a 200 response with no content, such as POST operation with an empty response, or a DELETE operation, `dtsgen` still produces this:

```
namespace Foo {
  ...
  namespace Responses {
    export interface $200 {
    }
  }
}
```

Wouldn't it make more sense to define the response as `void`?

```
namespace Foo {
  ...
  namespace Responses {
    export type $200 = void;
  }
}
```

Some background: in my implementation, I'm using a framework where it's really useful if I can define the operations such as:

```
const Operations = {
  foo: Operation<Foo.RequestBody, Foo.Responses.$200>,
  bar: Operation<Bar.RequestBody, Bar.Responses.$200>,
};
```

This now means that my `foo` operation must return an empty object `{}` if I want to reference the `Responses` namespace properly, even though it is in fact a void operation since the OpenAPI definition looks like this:

```
      responses:
        '200':
          description: OK
```

Actually, for me it might be useful also if `RequestBody` was always defined, so that for operatiosn without any request body (such as GET methods) it would be an alias for `void`, but I guess that's more opinionated?

Possibly I could solve this by writing a custom plugin that transforms empty responses to `void`, but at that point it might be lacking the context to decide if the operation is in fact without response or if it actually returns an empty JSON object.

**Comment by horiuchi** [comment]
@henhal Sorry for the delay, but we added support for void type in v3.7.0.

If you explicitly specify that the response does not exist (`schema: false`), it will be `void` type.
The result will be the same as in the previous schema.
