### ISSUE TITLE
The TypeScript AST should not be used in internal implementations. Instead, use ESTree.

### ISSUE THREAD

**Issue by horiuchi** [horiuchi/dtsgenerator#447]

**Comment by silesky** [comment]
@horiuchi interested to know why?

**Comment by horiuchi** [comment]
@silesky Sorry late response.

> If the plugin depends on TypeScript AST, it would have to always refer to the same version of TypeScript as the main dtsgenerator. However, that would make it difficult to maintain each of the main and all plugins, so we want the plugin interface to be independent of the TypeScript version.
via. https://github.com/horiuchi/dtsgenerator/pull/458#issuecomment-745079252

**Comment by horiuchi** [comment]
This problem was solved in a different way, so close
