### ISSUE TITLE
Support for more media types

### ISSUE THREAD

**Issue by wszydlak** [horiuchi/dtsgenerator#450]
Can you please add support for all supported media types by swagger/openapi?
Currently for example *multipart* media types are not supported resulting with:
```
Error: The $ref targets root is not found:
```

Example: https://codesandbox.io/s/mystifying-shadow-lcbmb?file=/schema.yaml:305-362

Changing lines in schema.yaml from multipart to application/json results with everything working fine.

*dtsgenerator* should support all media types supported by swagger/openapi: https://swagger.io/docs/specification/describing-request-body/

**Comment by wszydlak** [comment]
On the other hand maybe there should be some option to skip unsupported types, but do not generate error?

**Comment by ptu14** [comment]
when can I expect this fix? it is kind of blocking me right now

**Comment by wiru123321** [comment]
Is there any solution to this problem?

**Comment by wszydlak** [comment]
@horiuchi please review #455 , this could fix this problem.
