### ISSUE TITLE
Invalid Typescript generated with "declare is namespace" when using replace-namespace plugin and typescript 4

### ISSUE THREAD

**Issue by henhal** [horiuchi/dtsgenerator#453]
This has puzzled me for a while. 
In a project I was using TypeScript ^3.9.5 and dtsgen was working fine, producing schemas and paths such as:

```
declare namespace Paths {
  ...
}
```

I then updated typescript to ^4 and now dtsgen fails to produce valid TS; every `declare` is followed by the word `is`:

```
declare is namespace Paths {
  ...
}
```
![Skärmbild från 2020-10-21 11-04-14](https://user-images.githubusercontent.com/9608258/96698271-34acfa00-138d-11eb-8bc6-7ee78558db11.png)

This happens consistently for any API if using replace-namespace together with TypeScript v4.
Only by downgrading to TypeScript 3.9.x I was able to produce valid files.
Does the addition of `is` ring any bells?

**Comment by henhal** [comment]
This seems to be caused by the replace-namespace plugin. In my example with the petstore I had mistakenly included a dtsgen.json file.  So it has nothing to do with TS3 vs TS4.

However, I'm still confused as to why this happens in some projects and not in others.
I have verified that the replace-namespace plugin version 1.3.2 is installed both locally and globally.
But:

* After installing globally and NOT using `npx` it works
* If using `npx` but having dtsgenerator 3.3.1 and replace-namespace 1.3.2 locally, it fails.

**Comment by crizo23** [comment]
This issue is already filed here: https://github.com/dtsgenerator/replace-namespace/issues/2

**Comment by wszydlak** [comment]
Hi there, i figured out what is happening:

dtsgenerator uses typescript 3 (which has `SyntaxKind.DeclareKeyword = 130`) while in typescript 4 `SyntaxKind.DeclareKeyword=133`

If you use plugin with typescript 4 it is with conflict with dtsgenerator which is using typescript 3

So there are 2 ways:
1) Enforce plugin to use same version as dtsgenerator
2) Add ability for dtsgenerator to be used with typescript 4 (I think this should be recommended way)
3) Plugin should have correct peerDependencies to dtsgenerator and typescript (?)

Probably that was applicable also to unexpected `any` word.

**Comment by wszydlak** [comment]
Maybe event typescript should not be dependency but peerDependency of dtsgenerator.

**Comment by wszydlak** [comment]
I just added #462

**Comment by wszydlak** [comment]
I have prepared fix for replace-namespace: https://github.com/dtsgenerator/replace-namespace/pull/5

But this not resolve problem. Lets say:

1) I have some package which is using typescript 4.0
2) I want to use dtsgenerator (which is installing in deep *node_modules/dtsgenerator/node_modules* its own version of typescript
3) dtsgenerator plugin use my version of typescript (4.0), cause it is installed in *node_modules/@dtsgenerator/plugin*

For now ensuring same version in plugin and in dtsgenerator can solve the problem, but meybe solution with exporting typescript from `dtsgenerator` will be the best:

Lets export typescript from `core/index.ts`:

```ts
import * as ts from 'typescript';
export { ts }
```

Then in plugin import `typescript` from `dtsgenerator`:

```ts
import { ts } from 'dtsgenerator';
```

This could resolve conflicts between versions of typescript.

**Comment by horiuchi** [comment]
That sounds like a good idea! 👍

**Comment by horiuchi** [comment]
Completed to change the `ts` to export from `dtsgenerator`.
https://github.com/horiuchi/dtsgenerator/blob/master/src/core/type.ts#L13

And also, I updated all plugins!
Please update the `dtsgenerator` and `replace-namespace` plugin.
