### ISSUE TITLE
is it possible to keep enum values enums?

### ISSUE THREAD

**Issue by maapteh** [horiuchi/dtsgenerator#473]
Hi,

From swagger json i see service having:

```
"enum":["CUSTOMER","SUPPLIER","CARRIER"]
```
Now dtsGenerator generated Union type:

```
type: "CUSTOMER" | "SUPPLIER" | "CARRIER";
```

Is it possible to keep it enum? Its now superweird to create a mock using the type since i have to typecast the value.

**Comment by horiuchi** [comment]
In TypeScript, the use of enums is not recommended, so I am not going to support it.

**Comment by maapteh** [comment]
Hi Horiuchi do you have reference to this recommendation?
https://www.typescriptlang.org/docs/handbook/enums.html

for example when moving from api's to for example graphql enums just like in API's are strong mechanism to do for example comparisons and not code them yourself  foo === Bar.Foo :)

**Comment by joshuagraber** [comment]
> In TypeScript, the use of enums is not recommended, so I am not going to support it.

@horiuchi Who is making this recommendation? Enums are supported in the language, no?

Even if they're not recommended (again, by whom?), they can still be useful in some cases. For my use-case for instance, I'm attempting to generate types from a suite of APIs (each with an openapi schema) to use as the underlying types for a GraphQL layer. As @maapteh mentioned above, this would be [very useful](https://github.com/horiuchi/dtsgenerator/issues/473#issuecomment-778045442) in that context.

**Comment by maapteh** [comment]
@joshuagraber please look at Orval, see for example https://orval.dev/guides/enums where it even gives more options for enums. Orval follows all open api specs, but not the [security schema ones](https://github.com/orval-labs/orval/issues/885#issuecomment-2137765293). All Models created should be nicely usable for your GQL.
