### ISSUE TITLE
Feature: full support for `minItems` & `maxItems`

### ISSUE THREAD

**Issue by medfreeman** [horiuchi/dtsgenerator#476]
Hi!

First i want to thank you for your work, this project has been so useful in our company projects!
We developed a number of improvements internally and we'd like to contribute back to the project and also avoid using patches over your module in the future.
Every change we developed has corresponding tests, some have corresponding options flags when really necessary, and to possibly avoid breaking changes. 

For reference, in addition to this one, that's what we have in store (you can always have a look here: https://github.com/medfreeman/dtsgenerator/network):
- support for `additionalItems`
- fix specific typescript transforms in plugins not producing changes at all (by changing the way the `generate` handles writing transform results)
- fix nested `oneOf` & `anyOf` that can produce incorrect children
- have free-form objects generate a index signature instead of `unknown`
- changes about the handling of `not` --> `void` types that can be incorrect in specific scenarios
- `patternProperties` possibly generating two index signatures, that don't pass strict mode (atm i disabled the relevant code internally and did not come up with a fix)

This will probably be kept private, unless it can be of interest to you, but we have also developed two plugins internally:
- one that adds an `export` keyword before each top-level `declare namespace` statement
- one that extracts generated interface & namespace names and their possible correspondence to schema ids

**Comment by medfreeman** [comment]
List of changes the corresponding PR introduces:

- support for `minItems` & `maxItems` when having `items` as an object
- `strictArraySize` option with its default set to false (to opt-in into the behavior and incidentally avoid a breaking change) that generates tuples with correct size and possible rest arguments
- corresponding optional `strict` snapshot tests (e.g. support for `test/snapshots/json-schema-draft-07/schema/_config_strict.json`, `test/snapshots/json-schema-draft-07/schema/_expected_strict.d.ts`)
- proper reset of options between tests using `clearToDefault` from `core/config` instead of `commandOptions` (it didn't manifest until now because the settings were always the same for tuple tests before my changes)
- update `SupportedFeatures.md`

PR: #477

**Comment by horiuchi** [comment]
Released by v3.8.0
