### ISSUE TITLE
Feature: support for `additionalItems`

### ISSUE THREAD

**Issue by medfreeman** [horiuchi/dtsgenerator#481]
Hi, here's the next contribution.

This adds support for `additionalItems` by:
- adding an optional 4th `additionalItems` argument to the `buildTupleTypeNode` astBuilder function, which will pass the additionalItems schema instead of the `any` keyword if present
- update `generateArrayTypeProperty` function to include, after normalization & type property generation, the `additionalItems` type to `buildSimpleArrayNode` & `buildTupleTypeNode` branches
- add corresponding `array` & `tuple` tests
- update the feature table

#480

**Comment by horiuchi** [comment]
published bu v3.9.0
