### ISSUE TITLE
Using official `ts.factory` api returning new nodes in plugin transforms does not result in modified output

### ISSUE THREAD

**Issue by medfreeman** [horiuchi/dtsgenerator#484]
The recommended / official way to do ts code transforms is as follows (example from one of our plugins):

_This takes all top-level `declare namespace` statements in the output file and prefixes them with the `export` keyword._

```typescript
import { Plugin, PluginContext, ts } from 'dtsgenerator';

const packageJson = require('../package.json');

/**
 * @public
 */
const plugin: Plugin = {
  meta: {
    name: packageJson.name,
    version: packageJson.version,
    description: packageJson.description
  },
  postProcess
};

async function postProcess(
  _pluginContext: PluginContext
): Promise<ts.TransformerFactory<ts.SourceFile> | undefined> {
  return addNamespaceExportKeywordTransform;
}

function addNamespaceExportKeywordTransform(context: ts.TransformationContext) {
  return function addNamespaceExportKeyword(root: ts.SourceFile): ts.SourceFile {
    function visit(node: ts.Node): ts.VisitResult<ts.Node> {
      if (ts.isSourceFile(node)) {
        return ts.visitEachChild(node, visit, context);
      } else if (ts.isModuleDeclaration(node)) {
        const hasExportKeywordModifier =
          node.modifiers?.find((n) => n.kind === ts.SyntaxKind.ExportKeyword) !== undefined;

        if (!hasExportKeywordModifier) {
          return ts.factory.updateModuleDeclaration(
            node,
            node.decorators,
            [
              ts.factory.createModifier(ts.SyntaxKind.ExportKeyword),
              ...(node.modifiers !== undefined ? node.modifiers : [])
            ],
            node.name,
            node.body
          );
        }
      }
      return node;
    }

    return ts.visitNode(root, visit);
  };
}

export default plugin;
```

At the moment no change is visible when this plugin is enabled, as opposed to your plugins (i.e. https://github.com/dtsgenerator/replace-namespace/blob/master/index.ts) where you modify the root node in-place.
I'm 99% sure that's the reason, but perhaps it'd be nice to test my changes with your plugins.

The PR introduces the recommended / official way to apply transforms, which works with this approach.

Let me know what you think about this.

PR: #483

**Comment by horiuchi** [comment]
@medfreeman  Thank you very much.
I will merge this change.

I found very little documentation on how to use the typescript factory API.
I had no choice but to implement it by looking at the TypeScript source and so on.
So there may still be some problems.
