### ISSUE TITLE
improvement: support freeform objects w/ index signature instead of unknown keyword

### ISSUE THREAD

**Issue by medfreeman** [horiuchi/dtsgenerator#489]
Hi !

This change improves the output of objects without properties by generating an object type with an index signature: `{ [key: string]: any }`.

Now that i think of it, perhaps it'd be better to have `{ [key: string]: unknown }` instead?

Thanks

PR: #488

**Comment by horiuchi** [comment]
Thank you for your contribution! 👍 

The type to change seems to be `{ [key: string]: any }`.
`Record<string, any>` is also good, but it's the same either way.

The `{[key: string]: unkown}` type seems to be treated differently from `Record<string, any>`, as shown below.
https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#-k-string-unknown--is-no-longer-a-wildcard-assignment-target

In fact, in the following code, only the case of `Record<string, unknown>` in line 15 causes a compilation error. For this replacement type, `Record<string, any>` seems to be a better choice.
https://typescript-play.js.org/?target=7#code/C4TwDgpgBAglC8UBKEDGB7ATgEwDwGdhMBLAOwHMAaKAQ1JAD4BuAKFEigFUFk0s9CJCtQCupANal0Ad1LMWLMsAiYAZjVTQAklADeLKFFXp0ALiikRAWwBGK1gF8WGUoSjFzOxLqMnzARigHVmd0V2Baf3M4b18zKEDg0PDaACZonmJWFzcaAGYMxH9ssNyAFkKLEQAbapKUmgBWSrFsCFUyCGx6txEorh4fY3jEnoiRdIHELOTegqmEsagRCoXLWqWRZoXW9s7u2Yj0frFJGVJBuICgpfRJ06lZTNv5h-OeYsOodFW3p8R1nUvuhtn8Lohdh1SF1WEA

**Comment by medfreeman** [comment]
Makes sense, wasn't sure about this behavior even if i encountered it lots of time already.
So i think the PR is correct as is then.
Thanks!
