### ISSUE TITLE
choice between interface or class

### ISSUE THREAD

**Issue by JBBianchi** [horiuchi/dtsgenerator#506]
Hi,

At the moment, when possible, the tool outputs an interface. I was wondering if it would be possible to give the possibility to output a class instead. For instance, if the config have `outputClass: true`, it would create classes instead of interfaces.

One step further that would be nice, it to add cross cut methods for plugins to:
- add imports
- add the possibility for the class to extend a base class or to implement interfaces
- change the constructor signature
- do something/add some code at the beginning of the constructor
- do something/add some code at the beginning of the end
- add some methods to the class
- add decorators to class
- add decorators to properties

**Comment by horiuchi** [comment]
I'm sorry, I can't imagine what I would use it for, but what exactly would you need it for?

Also, the output of the dtsgenerator is .d.ts, so it can only output types, so the scope of expression is the same for both interfaces and classes. Of course, an interface can be extended, and constructors and methods can be added.
I don't understand why you want to change to class.

**Comment by JBBianchi** [comment]
Types and interfaces don't exist at runtime, they cannot be reflected/decorated, you cannot define defaults/logic inside them and so on.

**Comment by horiuchi** [comment]
After all, I can't imagine what I would use the function for.

However, if you need it, you can add a post-processor as a plug-in, and I think that will work.
