### ISSUE TITLE
File 'types.d.ts' is not a module.

### ISSUE THREAD

**Issue by yidongw** [horiuchi/dtsgenerator#508]
It will give me this error when I trying to import the generated type file.

After I added `export` before `declare namespace *`, then it worked, but I don't want to manually do that every time I generate the type file. 

Maybe I'm not using the type file correctly. How should I use it? Or how should I configure it so that it has `export` in front of the `declare namespace`?

Thanks

**Comment by horiuchi** [comment]
Since the files generated by the `dtsgeneerator` are type definition files, there is no need to import them;
you can use the types defined in the `types.d.ts` files by passing them to the typescript compiler as source files.
