### ISSUE TITLE
How do I suppress long prefices?

### ISSUE THREAD

**Issue by obgibson** [horiuchi/dtsgenerator#554]
I ran dtsgenerator yesterday and got types like 

`UserStatusResponse`

Today I ran again and got types like 

`GithubComMyCompanyFoundationBackendInternalOnboardingServerUserStatusResponse `

What did I do wrong? And how to I get the shorter type names again?

**Comment by obgibson** [comment]
nm - I realised my source swagger files changed

**Comment by horiuchi** [comment]
@obgibson Sorry for the late reply.

I'm glad you found the cause.
Please let me know if you encounter any more problems.
