### ISSUE TITLE
All interface properties made optional

### ISSUE THREAD

**Issue by henriksjodahl** [horiuchi/dtsgenerator#562]
I've got this problem where when generating interfaces all properties become optional, even if they are not in the swagger.json file.

swagger.json
```
      "UserLoginUserData": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "email": {
            "type": "string"
          },
          "name": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
```

generated interface
```
          export interface UserLoginUserData {
            id?: string; // uuid
            email?: string;
            name?: string | null;
          }
```

the command i run
```dtsgen --config dtsgen.json --out types/api.generated.d.ts```

dtsgen.json
```
{
  "input": {
    "files": ["swagger.json"]
  },
  "target": "ESNext"
}
```

**Comment by horiuchi** [comment]
The `required` property is not set, so everything is optional.
Please refer to the below page.
https://swagger.io/specification/#parameter-object

**Comment by henriksjodahl** [comment]
Wow you are right, i should have seen that. Sorry!
