### ISSUE TITLE
nested interfaces?

### ISSUE THREAD

**Issue by busticated** [horiuchi/dtsgenerator#563]
hey there 👋 

thanks for making this lib 🙏  i'm seeing nested `export interface` declarations like:

```ts
export interface ConstraintSetDto {
  state: string;
  export interface rules {
    [key: string]: any;
  }[];
}
```

from an OpenAPI v3.1.0 doc ([source](https://app.quilter.ai/openapi.json))

do you support this version of OpenAPI? 

thanks again 👍

**Comment by horiuchi** [comment]
@busticated 
Thank you for using this! 👍 

I have tried using the latest version at local env and cannot seem to reproduce this result.
The output results here are as follows, and there seems to be no problem.
```
declare namespace Components {
    namespace Schemas {
~~~~~
        /**
         * ConstraintSetDto
         */
        export interface ConstraintSetDto {
            /**
             * State
             */
            state: string;
            /**
             * Rules
             */
            rules: {
                [key: string]: any;
            }[];
        }
~~~~~
    }
}
```

Please let me know what version you are using and if there are any non-default configuration items.

**Comment by busticated** [comment]
thanks for taking a look 🙏 

i'm using:

```
>>npm ls dtsgenerator    
my-app@0.1.0 /Users/me/code/my-app
├─┬ @dtsgenerator/replace-namespace@1.6.0
│ └── dtsgenerator@3.19.1 deduped
└── dtsgenerator@3.19.1
```

...and calling the programmatic API:

```ts
async function generateWithDTSGen(destination: string, schema) {
	const { default: dtsgen, parseSchema } = dtsgenerator;

	const output = await dtsgen({
		contents: [parseSchema(schema)],
		config: {
			plugins: {
				'@dtsgenerator/replace-namespace': {
					map: [
						{
							from: ['Components', 'Schemas'],
							to: ['API', 'Entities'],
						},
					],
				},
			},
		},
	});

	await fs.outputFile(destination, formatOutput(output));
}
```

...where `schema` is the JSON-parsed `openapi.json` i linked above. running with or without the `plugins` option block, i get the same result as i shared above.

**Comment by busticated** [comment]
oh lol 🤦 

i found the issue 👉 `formatOutput()` - copy-pasta from an unrelated debug attempt 🤗 

closing this, sorry for the noise 🙏
