### ISSUE TITLE
TypeError: example.split is not a function

### ISSUE THREAD

**Issue by poislagarde** [horiuchi/dtsgenerator#67]
When the schema contains non-string examples, the generator crashes with error:
> TypeError: example.split is not a function

example schema:

```json
{
  "modelYear": {
    "type": "string",
    "example": 2013
  }
}
```

**Comment by horiuchi** [comment]
Thank you for reporting error 😄 
I will fix this issue.

**Comment by poislagarde** [comment]
Awesome! Thank you @horiuchi
