### ISSUE TITLE
npm install fails on dependencies not included such as Python!

### ISSUE THREAD

**Issue by Cyberider** [horiuchi/dtsgenerator#7]
![image](https://cloud.githubusercontent.com/assets/12577711/8768665/642ee9ea-2e3d-11e5-81fc-21a115734c3c.png)

**Comment by horiuchi** [comment]
Sorry I don't have windows environment.
For all I know `node-gyp` that build native library require `python`.
http://stackoverflow.com/questions/15126050/running-python-on-windows-for-node-js-dependencies

**Comment by Cyberider** [comment]
Thank you for your reply! I will try that direction of help from stackoverflow.
